### PR TITLE
Drivers v2 (with support for device grouping)

### PR DESCRIPTION
**Pull request by leolost2605**
[As suggested](https://github.com/elementary/switchboard-plug-about/pull/300#pullrequestreview-1887302903) this implements allowing to group drivers by device.
Since this [required](https://github.com/elementary/settings-daemon/pull/132#issuecomment-1950649413) quite a few more steps where different cli outputs have to be parsed, compared, compared again and then double checked, this PR should be tested thoroughly. I've tested with a nvidia card and there it works however I don't know how it will behave with two or more devices etc.

elementary/switchboard-plug-about#309

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This also needs to be able to be disabled since it only works in Ubuntu (or ported to use AppStream driver definitions through PackageKit).

**Comment by leolost2605** [comment]
It can be disabled via a meson option now (just like it was in appcenter) and is enabled by default

**Review by zeebok — APPROVED** [review]
Not sure how to test this really well, but the code seems good

**Comment by leolost2605** [comment]
I'd say let's merge this to get more testing in :)

**Pull request merged**
