### PR TITLE
Add ubuntu drivers backend

### LINKED ISSUE #140: Handle system driver management
This project from solus seems like a good starting point.
https://github.com/solus-project/linux-driver-management

### PR DESCRIPTION
**Pull request by leolost2605**
Fixes #140 

Should now be on par with what appcenter does. The only open question for me is this:

- [ ] Do we still need to install kernel headers like it's currently done in appcenter? I've recently seen a PR about adding them by default so I don't know?

### CODE REVIEW

**Comment by danirabbit** [comment]
@leolost2605 Yeah we've had people, especially with the nvidia driver, who want to switch to another version of the driver. It looks like Ubuntu lists them all as radios: https://linuxconfig.org/wp-content/uploads/2019/12/02-how-to-install-the-nvidia-drivers-on-ubuntu-20-04-focal-fossa-linux.png

**Comment by leolost2605** [comment]
Ok I finally got around to testing this at least with nvidia drivers and it should work now.

Some things to note:

- You currently can't remove drivers because that would require running autoremove and since it's currently the same in appcenter it's left to follow up PRs
- With nvidia drivers installing another one while one is already installed automatically removes the other one. They aren't shown with radio buttons because that would require either assuming all drivers with nvidia in their name are for the same device or redoing quite a lot of this and I kind of don't want to do either since I don't have a lot of time ATM. Also it is on par with appcenter and I would say even a bit more understandable for the user.
- elementary/switchboard-plug-about#300 is the corresponding UI PR

**Comment by leolost2605** [comment]
See #141 for v2 of this

**Comment by danirabbit** [comment]
Closing since we merged in the other version

**Pull request closed without merging**
