### PR TITLE
Set accent color based on wallpaper

### PR DESCRIPTION
**Pull request by meisenzahl**
https://github.com/elementary/granite/pull/122 inspired me to do this. The logic to extract the color is a 1:1 copy from @Philip-Scott's PR.

https://user-images.githubusercontent.com/10796736/111026176-4dc05100-83e9-11eb-92d4-c45fff84ffd9.mp4

This is a first draft where the logic and color handling still needs to be optimized.

@elementary/ux is this something you are interested in?

### CODE REVIEW

**Comment by cassidyjames** [comment]
I am super interested if it works well! I imagine we would add a “automatically select from wallpaper” option to the accent colors or something in case someone wanted to override this?

**Comment by donadigo** [comment]
I feel like at least for this purpose, we could use a different algorithm altogether, than the Palette one. As you can see, it's quite slow to compute the color and in this case. Here we actually have known colors we can set, so really, it's a matter of determining how much of each predefined color there is in the wallpaper, which should be faster than the Palette API, which needs to quantize and sort through a lot of pixels just to determine the dominant color.

**Comment by davidmhewitt** [comment]
I would suggest something like the following for an alternative algorithm.

Define a set of colour "bins", one matching each palette colour.

Sample every nth pixel of the image. We might only need to sample 1% of the pixels in the image to get a good result. So you could sample 1 pixel and then skip 99. We might need more if the results aren't good. But I don't think we'd need more than 10%, since most images are just large patches of mostly the same colour anyway.

For each sampled pixel, find the closest "bin" that matches that colour. There are plenty of colour distance algorithms to choose from.

Once you have a count of how many pixels fit in each bin, then the one with the highest count is your dominant colour.

**Comment by meisenzahl** [comment]
@cassidyjames yes exactly :slightly_smiling_face: I have created the key `set-accent-color-based-on-wallpaper` in the schema for enabling the feature.

I wanted to use the palette API to try out how well it works for a prototype.

Since there is interest, based on the suggestions I will optimize the algorithm for setting the color. Thanks for the suggestions!

**Comment by meisenzahl** [comment]
I implemented a simpler logic as a first draft. For this, the processing is already much faster.

The problem with this simple logic is that in some cases the dominant color is not a vibrant color you want to use to match the accent color:

https://user-images.githubusercontent.com/10796736/111075304-b2fa6c00-84e7-11eb-8b55-b8126aef3c36.mp4

**Comment by meisenzahl** [comment]
| Wallpaper                                                                                                              | Accent Color (`Palette.vala` vibrant)    | Accent Color (simple)                    |
| ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------- | ---------------------------------------- |
|              | <p style="color: #ed5353">strawberry</p> | <p style="color: #ed5353">strawberry</p> |
|  | <p style="color: #8a715e">cocoa</p>      | <p style="color: #8a715e">cocoa</p>      |
|       | <p style="color: #667885">slate</p>      | <p style="color: #667885">slate</p>      |
|              | <p style="color: #8a715e">cocoa</p>      | <p style="color: #667885">slate</p>      |
|              | <p style="color: #f9c440">banana</p>     | <p style="color: #f9c440">banana</p>     |
|               | <p style="color: #68b723">lime</p>       | <p style="color: #667885">slate</p>      |
|                   | <p style="color: #ed5353">strawberry</p> | <p style="color: #667885">slate</p>      |
|               | <p style="color: #3689e6">blueberry</p>  | <p style="color: #3689e6">blueberry</p>  |
|         | <p style="color: #667885">slate</p>      | <p style="color: #8a715e">cocoa</p>      |
|      | <p style="color: #8a715e">cocoa</p>      | <p style="color: #667885">slate</p>      |
|    | <p style="color: #28bca3">mint</p>       | <p style="color: #667885">slate</p>      |
|            | <p style="color: #de3e80">bubblegum</p>  | <p style="color: #de3e80">bubblegum</p>  |
|            | <p style="color: #a56de2">grape</p>      | <p style="color: #28bca3">mint</p>       |
|           | <p style="color: #a56de2">grape</p>      | <p style="color: #8a715e">cocoa</p>      |

**Comment by cassidyjames** [comment]
Hm, I would probably make different choices than either of those algorithms, but neither really stands out as exceptionally better than the other. I like the tendency of the slower one to pick out subtle accent colors (like the red in Mr. Lee), but it also missed on a couple as well.

Another consideration: what if we run the algorithm once per user wallpaper, and even pre-seed the known wallpapers with colors the design team finds aesthetically appropriate? GNOME has an XML format for wallpapers; I am not sure where the spec is, but we could ship our first-party wallpapers with color metadata in a similar format or perhaps embedded in EXIF data? Then we could only fall back to the color-picking algorithm when adding a wallpaper, and store it in the same way.

**Comment by cassidyjames** [comment]
And as another data point, these are my first-instinct accent colors I'd choose:

| Wallpaper                                                                                                              | `Palette.vala` vibrant                                                         | Simple                                                                         | Hand-picked                                                                    |
|------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|--------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
|              | #ed5353 **strawberry** | #ed5353 **strawberry** | #f37329 **orange**     |
|  | #8a715e **cocoa**      | #8a715e **cocoa**      | #8a715e **cocoa**      |
|       |  **slate**      |  **slate**      | #3689e6 **blueberry**  |
|              | #8a715e **cocoa**      |  **slate**      |  **slate**      |
|              | #f9c440 **banana**     | #f9c440 **banana**     | #f9c440 **banana**     |
|               | #68b723 **lime**       |  **slate**      | #68b723 **lime**       |
|                   | #ed5353 **strawberry** |  **slate**      | #ed5353 **strawberry** |
|               | #3689e6 **blueberry**  | #3689e6 **blueberry**  | #3689e6 **blueberry**  |
|         |  **slate**      | #8a715e **cocoa**      |  **slate**      |
|      | #8a715e **cocoa**      |  **slate**      | #3689e6 **blueberry**  |
|    | #28bca3 **mint**       |  **slate**      | #f37329 **orange**     |
|            | #de3e80 **bubblegum**  | #de3e80 **bubblegum**  | #de3e80 **bubblegum**  |
|            | #a56de2 **grape**      | #28bca3 **mint**       | #de3e80 **bubblegum**  |
|           | #a56de2 **grape**      | #8a715e **cocoa**      | #f37329 **orange**     |

**Comment by meisenzahl** [comment]
Right now I have hardcoded the colors in the code. But the specification for GNOME XML backgrounds allows to set a `primary-color`: https://help.gnome.org/admin/system-admin-guide/stable/backgrounds-extra.html.en

I will look at how we can provide this for our wallpapers.

**Comment by meisenzahl** [comment]
^ That didn't work. I have now put the accent color in the EXIF data of the wallpapers.

**Comment by cassidyjames** [comment]
@meisenzahl did this drop the automatic color detection in favor of EXIF data only?

**Comment by meisenzahl** [comment]
@cassidyjames the color should be determined with the simple algorithm if the image does not contain EXIF information. I'll just check this again.

**Comment by cassidyjames** [comment]
@meisenzahl ah, I was trying with a partially-transparent image which I think is confusing things. It does appear to work with regular backgrounds, though.

**Comment by cassidyjames** [comment]
@meisenzahl so, after talking with Dan, we wondered if this makes more sense to live in Gala since Gala is already looking at the wallpaper when it sets it for the panel transparency. I also think instead of a distinct GSetting, this should be triggered by the AccountsService "no preference" accent color, so we can show it as a radio button alongside the other accent colors.

**Comment by meisenzahl** [comment]
Closing in favor of https://github.com/elementary/gala/pull/1104

**Pull request closed without merging**
